site_name: lernOS Template Leitfaden
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Grundlagen:
      - Grundidee: 1-1-Grundidee.md
      - Lebenszyklus: 1-2-Lebenszyklus.md
      - Inhaltsverzeichnis: 1-3-Inhaltsverzeichnis.md
      - Inhalt: 1-4-Inhalt.md
      - Produktionskette: 1-5-Produktionskette.md
    - Lernpfad:
      - Überblick: 2-Lernpfad.md
    - Anhang:
      - Überblick: 3-Anhang.md
    - Links:
      - lernOS Website: https://lernos.org
      - lernOS Community: https://community.cogneon.de

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de
    features:
      - navigation.sections
    icon:
      logo: material/home
      repo: fontawesome/brands/github

repo_name: 'cogneon/lernos-template'
repo_url: 'https://github.com/cogneon/lernos-template'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/lern_os'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    disqus: lernos
